spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/trupal
    username: ${POSTGRES_USERNAME:postgres}
    password: ${POSTGRES_PASSWORD:password}
  liquibase:
    change-log: classpath:db/db.changelog-master.yaml

#Logging for database framework
logging:
  level:
    org:
      springframework:
        jdbc: DEBUG

app:
  domain: ${TRUID_EXAMPLE_DOMAIN:http://localhost:8080}

web:
  signup:
    success: ${app.domain}/truid/v1/presentation
    failure: ${app.domain}/signup/failure.html
  peer-to-peer: ${app.domain}/peer-to-peer

oauth2:
  clientId: ${TRUID_CLIENT_ID:test-client-id}
  clientSecret: ${TRUID_CLIENT_SECRET:test-client-secret}
  redirectUri:
    confirmSignup: ${TRUID_REDIRECT_URI_CONFIRMSIGNUP:${app.domain}/truid/v1/confirm-signup}
    completeSignup: ${TRUID_REDIRECT_URI_COMPLETESIGNUP:${app.domain}/truid/v1/complete-signup/create}
    create: ${TRUID_REDIRECT_URI_SIGNUP:${app.domain}/truid/v1/peer-to-peer/create}
    join: ${TRUID_REDIRECT_URI_JOIN:${app.domain}/truid/v1/peer-to-peer/join}
  truid:
    token-endpoint: ${TRUID_BASEPATH:https://api.truid.app}/oauth2/v1/token
    signup-endpoint: ${TRUID_BASEPATH:https://api.truid.app}/oauth2/v1/authorize/confirm-signup
    presentation-endpoint: ${TRUID_BASEPATH:https://api.truid.app}/exchange/v1/presentation
